-- Active: 1683725252949@@127.0.0.1@3306@ls

USE LS;

CREATE TABLE
    IF NOT EXISTS PERSON(
        PERSON_ID SMALLINT UNSIGNED,
        FNAME VARCHAR(20),
        LNAME VARCHAR(20),
        EYE_COLOR ENUM('BR', 'BL', 'GR'),
        BIRTH_DATE DATE,
        STREET VARCHAR(30),
        CITY VARCHAR(20),
        STATE VARCHAR(20),
        COUNTRY VARCHAR(20),
        POSTAL_CODE VARCHAR(20),
        CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID)
    );

CREATE TABLE
    IF NOT EXISTS FAVORITE_FOOD(
        PERSON_ID SMALLINT UNSIGNED,
        FOOD VARCHAR(20),
        CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID, FOOD),
        CONSTRAINT FK_FAV_FOOD_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID)
    );

SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE PERSON MODIFY PERSON_ID SMALLINT UNSIGNED AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;

INSERT INTO
    PERSON (
        PERSON_ID,
        FNAME,
        LNAME,
        EYE_COLOR,
        BIRTH_DATE
    )
VALUES (
        NULL,
        'WILLIAM',
        'TURNER',
        'BR',
        '1972-05-27'
    );

SELECT
    PERSON_ID,
    FNAME,
    LNAME,
    BIRTH_DATE
FROM PERSON;

SELECT
    PERSON_ID,
    FNAME,
    LNAME,
    BIRTH_DATE
FROM PERSON
WHERE PERSON_ID = 1;

SELECT
    PERSON_ID,
    FNAME,
    LNAME,
    BIRTH_DATE
FROM PERSON
WHERE LNAME = 'TURNER';

INSERT INTO favorite_food (`PERSON_ID`, `FOOD`) VALUES (1, 'PIZZA');

INSERT INTO
    favorite_food (`PERSON_ID`, `FOOD`)
VALUES (1, 'COOKIES');

INSERT INTO favorite_food (`PERSON_ID`, `FOOD`) VALUES (1, 'NACHOS');

SELECT FOOD FROM favorite_food WHERE `PERSON_ID`=1 ORDER BY `FOOD`;

INSERT INTO
    person (
        `PERSON_ID`,
        `FNAME`,
        `LNAME`,
        `EYE_COLOR`,
        `BIRTH_DATE`,
        `CITY`,
        `STREET`,
        `STATE`,
        `COUNTRY`,
        `POSTAL_CODE`
    )
VALUES (
        null,
        'Susan',
        'Smith',
        'BL',
        '1975-11-02',
        '23 Maple st.',
        'Arlington',
        'VA',
        'USA',
        '20220'
    );

SELECT * FROM person;

UPDATE PERSON
SET
    STREET = '1225 TREMONT ST.',
    `CITY` = 'BOSTON',
    STATE = 'MA',
    COUNTRY = 'USA',
    `POSTAL_CODE` = '02138'
WHERE `PERSON_ID` = 1;

UPDATE PERSON
SET
    STREET = '1225 TREMONT ST.',
    `CITY` = 'BOSTON',
    STATE = 'MA',
    COUNTRY = 'USA',
    `POSTAL_CODE` = '02138'
WHERE `PERSON_ID` < 10;

DELETE FROM person WHERE `PERSON_ID`=2;

SHOW TABLES;