-- Active: 1683725252949@@127.0.0.1@3306@ls

USE LS;

CREATE TABLE
    IF NOT EXISTS PERSON(
        PERSON_ID SMALLINT UNSIGNED,
        FNAME VARCHAR(20),
        LNAME VARCHAR(20),
        EYE_COLOR ENUM('BR', 'BL', 'GR'),
        BIRTH_DATE DATE,
        STREET VARCHAR(30),
        CITY VARCHAR(20),
        STATE VARCHAR(20),
        COUNTRY VARCHAR(20),
        POSTAL_CODE VARCHAR(20),
        CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID)
    );

CREATE TABLE
    IF NOT EXISTS FAVORITE_FOOD(
        PERSON_ID SMALLINT UNSIGNED,
        FOOD VARCHAR(20),
        CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID, FOOD),
        CONSTRAINT FK_FAV_FOOD_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID)
    );

SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE PERSON MODIFY PERSON_ID SMALLINT UNSIGNED AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;