-- Active: 1683725252949@@127.0.0.1@3306@books

CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE
    BOOK (
        ISBN CHAR(13) NOT NULL,
        MAIN_TITLE VARCHAR(255) NOT NULL,
        SUB_TITLE TEXT,
        EDITIONS SMALLINT,
        WORDS INT,
        YEAR SMALLINT,
        MONTH TINYINT,
        CONSTRAINT PK_BOOK PRIMARY KEY (ISBN)
    );

CREATE TABLE
    READING_RECORD (
        RECORD_ID INT UNSIGNED AUTO_INCREMENT,
        ISBN CHAR(13),
        BEGINNING_DATE DATE,
        ENDING_DATE DATE,
        CONSTRAINT PK_RECORDS PRIMARY KEY (RECORD_ID, ISBN),
        CONSTRAINT FK_RECORDS FOREIGN KEY (ISBN) REFERENCES BOOK (ISBN)
    );