-- Active: 1683725252949@@127.0.0.1@3306@sakila

SELECT
    CONCAT(
        CUST.LAST_NAME,
        ', ',
        CUST.FIRST_NAME
    ) AS FULL_NAME
FROM (
        SELECT
            FIRST_NAME,
            LAST_NAME,
            EMAIL
        FROM customer
        WHERE
            FIRST_NAME = 'JESSIE'
    ) AS CUST;

CREATE TEMPORARY
TABLE
    ACTORS_J(
        ACTOR_ID SMALLINT(5),
        FIRST_NAME VARCHAR(45),
        LAST_NAME VARCHAR(45)
    );

INSERT INTO ACTORS_J
SELECT
    ACTOR_ID,
    FIRST_NAME,
    LAST_NAME
FROM ACTOR
WHERE LAST_NAME LIKE 'J%';

SELECT * FROM ACTORS_J;

CREATE VIEW CUST_VW AS 
	SELECT
	    CUSTOMER_ID,
	    FIRST_NAME,
	    LAST_NAME,
	    ACTIVE
	FROM
CUSTOMER; 

SELECT FIRST_NAME, LAST_NAME FROM cust_vw WHERE `ACTIVE`=0;

SELECT
    CUSTOMER.FIRST_NAME,
    CUSTOMER.LAST_NAME,
    TIME(RENTAL.RENTAL_date) AS RENTAL_TIME
FROM CUSTOMER
    INNER JOIN rental ON CUSTOMER.customer_id = RENTAL.customer_id
WHERE
    DATE(RENTAL.rental_date) = '2005-06-14';

SELECT * FROM rental;